---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: './roles'
  environments_path: './environments'
  data_bags_path: './data_bags'
  client_rb:
    environment: 'development'

platforms:
  - name: ubuntu-16.04
    driver:
      box: 'ubuntu/xenial64'
      customize:
        memory: 1024
        cpus: 1

suites:
  - name: default
    run_list:
      - recipe[get-native.com-cookbook::default]
  - name: web
    run_list:
      - role[web-server]
    attributes:
      get-native:
        server_name: 'get-native.com.local'
  - name: db
    run_list:
      - role[db-server]
