---
driver:
  name: docker

driver_config:
  forward: 22

provisioner:
  name: chef_zero
  roles_path: './roles'
  environments_path: './environments'
  data_bags_path: './data_bags'
  client_rb:
    environment: 'development'

platforms:
  - name: ubuntu-16.04
    driver_config:
      image: ubuntu:16.04

suites:
  - name: default
    run_list:
      - recipe[cookbook.getnative.org::default]
  - name: web
    run_list:
      - role[web]
    attributes:
      getnative:
        server_name: 'localhost'
  - name: db
    run_list:
      - role[db]
    attributes:
      getnative:
        server_name: 'localhost'
