---
driver:
  name: gce
  project: stg-get-native
  zone: us-west1-b
  disk_size: 10
  machine_type: f1-micro
  network: default
  preemptible: false

provisioner:
  name: chef_zero
  roles_path: './roles'
  environments_path: './environments'
  data_bags_path: './data_bags'
  client_rb:
    environment: 'development'

platforms:
  - name: ubuntu-16.04
    driver:
      image_project: ubuntu-os-cloud
      image_family: ubuntu-1604-lts

suites:
  - name: default
    run_list:
      - recipe[get-native.com-cookbook::default]
  - name: web
    run_list:
      - role[web]
    attributes:
      get-native:
        server_name: 'localhost'
  - name: db
    run_list:
      - role[db]
    attributes:
      get-native:
        server_name: 'localhost'

transport:
  username: chef
  ssh_key:
    - ~/.ssh/google-compute-engine/chef
