---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
    driver:
      box: 'ubuntu/xenial64'

suites:
  - name: default
    run_list:
      - recipe[get-native.com-cookbook::default]
  - name: web
    run_list:
      - recipe[get-native.com-cookbook::bootstrap]
      - recipe[get-native.com-cookbook::add-user]
      - recipe[get-native.com-cookbook::authorized-keys]
      - recipe[get-native.com-cookbook::deploy-key]
      - recipe[get-native.com-cookbook::apache2]
      - recipe[get-native.com-cookbook::mysql-client]
      - recipe[get-native.com-cookbook::nodejs]
      - recipe[get-native.com-cookbook::letsencrypt]
    data_bags_path: './data_bags'
    roles_path: './roles'
  - name: db
    run_list:
      - recipe[get-native.com-cookbook::db-server]
    data_bags_path: './data_bags'
