---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: './data_bags'
  roles_path: './roles'

platforms:
  - name: ubuntu-16.04
    driver:
      box: 'ubuntu/xenial64'

suites:
  - name: default
    run_list:
      - recipe[get-native.com-cookbook::default]
  - name: web
    run_list:
      - role[web-server]
  - name: db
    run_list:
      - role[db-server]
