---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
    driver:
      box: 'ubuntu/xenial64'

suites:
  - name: default
    run_list:
      - recipe[get-native.com-cookbook::default]
  - name: web
    run_list:
      - recipe[get-native.com-cookbook::web-server]
    data_bags_path: './data_bags'
  - name: db
    run_list:
      - recipe[get-native.com-cookbook::db-server]
    data_bags_path: './data_bags'
