name 'get-native.com-cookbook'
maintainer 'Hank Ehly'
maintainer_email 'henry.ehly@gmail.com'
license 'all_rights'
description 'Installs/Configures get-native.com db/web servers'
long_description 'Installs/Configures get-native.com db/web servers'
version '0.2.1'

depends 'apache2', '~> 3.3.0'
depends 'apt', '~> 6.1.0'
depends 'build-essential', '~> 8.0.2'
depends 'compat_resource', '~> 12.19.0'
depends 'deploy_key', '~> 0.3.0'
depends 'locale', '~> 2.0.1'
depends 'mysql', '~> 8.3.1'
depends 'nodejs', '~> 3.0.0'
depends 'openssh', '~> 2.4.0'
depends 'sudo', '~> 3.5.0'
