name 'get-native.com-cookbook'
maintainer 'Hank Ehly'
maintainer_email 'henry.ehly@gmail.com'
license 'all_rights'
description 'Installs/Configures get-native.com db/web servers'
long_description 'Installs/Configures get-native.com db/web servers'
version '0.2.6'

depends 'apache2', '~> 5.0.0'
depends 'apt', '~> 6.1.2'
depends 'build-essential', '~> 8.0.3'
depends 'locale', '~> 2.0.1'
depends 'mysql', '~> 8.4.0'
depends 'nodejs', '~> 4.0.0'
depends 'openssh', '~> 2.4.1'
depends 'sudo', '~> 3.5.3'
