name 'cookbook.getnativelearning.com'
maintainer 'Hank Ehly'
maintainer_email 'henry.ehly@gmail.com'
license 'all_rights'
description 'Installs/Configures getnativelearning.com db/web servers'
long_description 'Installs/Configures getnativelearning.com db/web servers'
version '0.2.6'

depends 'apache2', '~> 5.0.1'
depends 'apt', '~> 6.1.4'
depends 'build-essential', '~> 8.0.3'
depends 'locale', '~> 2.0.1'
depends 'mysql', '~> 8.5.1'
depends 'nodejs', '~> 4.0.0'
depends 'openssh', '~> 2.6.0'
depends 'sudo', '~> 3.5.3'
depends 'logrotate', '~> 2.2.0'
