version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: buildpack-deps:xenial
    steps:
      - checkout
      - run:
        - wget https://packages.chef.io/files/stable/chefdk/1.2.22/ubuntu/14.04/chefdk_1.2.22-1_amd64.deb
        - sudo dpkg -i chefdk_1.2.22-1_amd64.deb
        - sudo chef gem install kitchen-docker
      - run:
        - chef exec berks install
        - KITCHEN_YAML=".kitchen.docker.yml" chef exec kitchen test
general:
  branches:
    only:
      - master